project:
  type: website

website:
  title: "AHHHHHHhsana"
  favicon: images/favicon.png
  search: false # Turns off search
  navbar:
    right:
      - href: posts/general/index.qmd
        text: General
      - href: posts/random/index.qmd
        text: Random Shit
      - href: posts/shower-thoughts/index.qmd
        text: Shower Thoughts
      - href: posts/self-help/index.qmd
        text: Self Help
    left:
      - href: posts/bluest-eye/index.qmd
        text: "<span class='book-btn'>The Bluest Eye</span>"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

