project:
  type: website

website:
  title: "AHHHHHHhsana"
  favicon: images/favicon.png
  search: false # Turns off search
  navbar:
    right:
      - href: posts/general/index.qmd
        text: "<span class='tag-btn'>General</span>"
      - href: posts/random/index.qmd
        text: "<span class='tag-btn'>Random</span>"
      - href: posts/shower-thoughts/index.qmd
        text: "<span class='tag-btn'>Shower Thoughts</span>"
      - href: posts/self-help/index.qmd
        text: "<span class='tag-btn'>Self Help</span>"
    left:
      - href: posts/bluest-eye/index.qmd
        text: "<span class='book-btn'>The Bluest Eye</span>"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

